// <auto-generated />
using System;
using Legacy.Maliev.QuotationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.QuotationService.Data.Migrations.Quotation
{
    [DbContext(typeof(QuotationDbContext))]
    [Migration("20260715051625_InitialQuotationPostgresCompatibility")]
    partial class InitialQuotationPostgresCompatibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("CurrencyID");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerID");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fob")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("FOB");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("InvoiceID");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<decimal?>("QuotedAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComputedColumnSql("(\"Total\" - \"WithholdingTax\")::numeric(18,2)", true);

                    b.Property<string>("ShippedVia")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Terms")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Vat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("WithholdingTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Quotation", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.QuotationFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("QuotationID");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuotationFile", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.QuotationOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("OrderID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("QuotationID");

                    b.Property<decimal?>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComputedColumnSql("(\"UnitPrice\" * \"Quantity\")::numeric(18,2)", true);

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.QuotationOrderLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("OrderID");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer")
                        .HasColumnName("QuotationID");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuotationHasOrder", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.QuotationFile", b =>
                {
                    b.HasOne("Legacy.Maliev.QuotationService.Domain.Quotation", "Quotation")
                        .WithMany("Files")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuotationFile_Quotation");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.QuotationOrderItem", b =>
                {
                    b.HasOne("Legacy.Maliev.QuotationService.Domain.Quotation", "Quotation")
                        .WithMany("OrderItems")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Quotation");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.QuotationOrderLink", b =>
                {
                    b.HasOne("Legacy.Maliev.QuotationService.Domain.Quotation", "Quotation")
                        .WithMany("Orders")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuotationHasOrder_Quotation");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.Quotation", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("OrderItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
