apiVersion: v1
kind: Service
metadata:
  name: legacy-maliev-quotation-service
  namespace: maliev-legacy
  labels:
    app.kubernetes.io/name: legacy-maliev-quotation-service
    app.kubernetes.io/part-of: maliev-legacy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: legacy-maliev-quotation-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
