apiVersion: v1
kind: ServiceAccount
metadata:
  name: legacy-maliev-quotation
  namespace: maliev-legacy
  labels:
    app.kubernetes.io/name: legacy-maliev-quotation-service
    app.kubernetes.io/part-of: maliev-legacy
automountServiceAccountToken: false
