// <auto-generated />
using System;
using Legacy.Maliev.QuotationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.QuotationService.Data.Migrations.QuotationRequest
{
    [DbContext(typeof(QuotationRequestDbContext))]
    [Migration("20260912163831_AddRequestQualificationContract")]
    partial class AddRequestQualificationContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.QuotationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<bool?>("Done")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("InternalComment")
                        .HasColumnType("text");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("QualificationState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("unreviewed");

                    b.Property<DateTime?>("QualificationStateChangedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("QualificationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("TaxIdentification")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId")
                        .HasDatabaseName("IX_Request_JourneyId")
                        .HasFilter("\"JourneyId\" IS NOT NULL");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Request_TransactionId")
                        .HasFilter("\"TransactionId\" IS NOT NULL");

                    b.ToTable("Request", null, t =>
                        {
                            t.HasCheckConstraint("CK_Request_QualificationState", "\"QualificationState\" IN ('unreviewed', 'qualified', 'not_qualified', 'duplicate', 'stale', 'incomplete')");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.QuotationRequestFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("ObjectName")
                        .HasColumnType("text");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("RequestID");

                    b.HasKey("Id");

                    b.ToTable("RequestFile", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.RequestCreateIdempotency", b =>
                {
                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("RequestID");

                    b.HasKey("KeyHash");

                    b.ToTable("RequestCreateIdempotency", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.RequestQualificationAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Completeness")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("RequestID");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UnmatchedClassification")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId")
                        .HasDatabaseName("IX_RequestQualificationAudit_JourneyId");

                    b.HasIndex("RequestId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestQualificationAudit_RequestID_IdempotencyKey");

                    b.ToTable("RequestQualificationAudit", null, t =>
                        {
                            t.HasCheckConstraint("CK_RequestQualificationAudit_DuplicateCount", "\"DuplicateCount\" >= 0");

                            t.HasCheckConstraint("CK_RequestQualificationAudit_NewState", "\"NewState\" IN ('unreviewed', 'qualified', 'not_qualified', 'duplicate', 'stale', 'incomplete')");

                            t.HasCheckConstraint("CK_RequestQualificationAudit_Reason", "\"NewState\" = 'qualified' OR NULLIF(BTRIM(\"Reason\"), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.QuotationService.Domain.RequestQualificationAudit", b =>
                {
                    b.HasOne("Legacy.Maliev.QuotationService.Domain.QuotationRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RequestQualificationAudit_Request");
                });
#pragma warning restore 612, 618
        }
    }
}
