name: Build and test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    env:
      MalievWorkspaceRoot: ${{ github.workspace }}/.dependencies
    steps:
      - name: Check out QuotationService
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Check out Legacy.Maliev.ServiceDefaults
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: MALIEV-Co-Ltd/Legacy.Maliev.ServiceDefaults
          ref: 67cd84ccd47be656383b0025e9f2b8d1d3f0eb36
          path: .dependencies/Legacy.Maliev.ServiceDefaults
          persist-credentials: false
      - name: Check out Legacy.Maliev.CompatibilityContracts
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: MALIEV-Co-Ltd/Legacy.Maliev.CompatibilityContracts
          ref: 95c62eb6209411f5aada443b315447a2f76ca0cd
          path: .dependencies/Legacy.Maliev.CompatibilityContracts
          persist-credentials: false
      - name: Validate .NET solution
        uses: MALIEV-Co-Ltd/Legacy.Maliev.Workflows/actions/dotnet-validate@6017816fa67f369d785ed30794f002cfd6299af7
        with:
          solution: Legacy.Maliev.QuotationService.slnx
          use-local-maliev-dependencies: 'true'
